name: Esegui Azioni di GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Configura il token
        run: echo "GH_TOKEN=${{ secrets.PAT }}" >> $GITHUB_ENV

      - name: Usa il token per interagire con l'API
        run: |
          curl -H "Authorization: token $GH_TOKEN" https://api.github.com/user